// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ArmMotorsInt64PubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _FAST_DDS_GENERATED_ARMMOTORSINT64_PUBSUBTYPES_H_
#define _FAST_DDS_GENERATED_ARMMOTORSINT64_PUBSUBTYPES_H_

#include <fastdds/dds/topic/TopicDataType.hpp>
#include <fastrtps/utils/md5.h>

#include "ArmMotorsInt64.h"


#if !defined(GEN_API_VER) || (GEN_API_VER != 1)
#error \
    Generated ArmMotorsInt64 is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER


#ifndef SWIG
namespace detail {

    template<typename Tag, typename Tag::type M>
    struct ArmMotorsInt64_Request_rob
    {
        friend constexpr typename Tag::type get(
                Tag)
        {
            return M;
        }
    };

    struct ArmMotorsInt64_Request_f
    {
        typedef bool ArmMotorsInt64_Request::* type;
        friend constexpr type get(
                ArmMotorsInt64_Request_f);
    };

    template struct ArmMotorsInt64_Request_rob<ArmMotorsInt64_Request_f, &ArmMotorsInt64_Request::m_arm>;

    template <typename T, typename Tag>
    inline size_t constexpr ArmMotorsInt64_Request_offset_of() {
        return ((::size_t) &reinterpret_cast<char const volatile&>((((T*)0)->*get(Tag()))));
    }
}
#endif

/*!
 * @brief This class represents the TopicDataType of the type ArmMotorsInt64_Request defined by the user in the IDL file.
 * @ingroup ArmMotorsInt64
 */
class ArmMotorsInt64_RequestPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef ArmMotorsInt64_Request type;

    eProsima_user_DllExport ArmMotorsInt64_RequestPubSubType();

    eProsima_user_DllExport virtual ~ArmMotorsInt64_RequestPubSubType() override;

    eProsima_user_DllExport virtual bool serialize(
            void* data,
            eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
            eprosima::fastrtps::rtps::SerializedPayload_t* payload,
            void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
            void* data) override;

    eProsima_user_DllExport virtual bool getKey(
            void* data,
            eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
            bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return is_plain_impl();
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
            void* memory) const override
    {
        new (memory) ArmMotorsInt64_Request();
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;

private:

    static constexpr bool is_plain_impl()
    {
        return 1ULL == (detail::ArmMotorsInt64_Request_offset_of<ArmMotorsInt64_Request, detail::ArmMotorsInt64_Request_f>() + sizeof(bool));

    }};

#ifndef SWIG
namespace detail {

    template<typename Tag, typename Tag::type M>
    struct ArmMotorsInt64_Reply_rob
    {
        friend constexpr typename Tag::type get(
                Tag)
        {
            return M;
        }
    };

    struct ArmMotorsInt64_Reply_f
    {
        typedef int64_t ArmMotorsInt64_Reply::* type;
        friend constexpr type get(
                ArmMotorsInt64_Reply_f);
    };

    template struct ArmMotorsInt64_Reply_rob<ArmMotorsInt64_Reply_f, &ArmMotorsInt64_Reply::m_result>;

    template <typename T, typename Tag>
    inline size_t constexpr ArmMotorsInt64_Reply_offset_of() {
        return ((::size_t) &reinterpret_cast<char const volatile&>((((T*)0)->*get(Tag()))));
    }
}
#endif

/*!
 * @brief This class represents the TopicDataType of the type ArmMotorsInt64_Reply defined by the user in the IDL file.
 * @ingroup ArmMotorsInt64
 */
class ArmMotorsInt64_ReplyPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef ArmMotorsInt64_Reply type;

    eProsima_user_DllExport ArmMotorsInt64_ReplyPubSubType();

    eProsima_user_DllExport virtual ~ArmMotorsInt64_ReplyPubSubType() override;

    eProsima_user_DllExport virtual bool serialize(
            void* data,
            eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
            eprosima::fastrtps::rtps::SerializedPayload_t* payload,
            void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
            void* data) override;

    eProsima_user_DllExport virtual bool getKey(
            void* data,
            eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
            bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return is_plain_impl();
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
            void* memory) const override
    {
        new (memory) ArmMotorsInt64_Reply();
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;

private:

    static constexpr bool is_plain_impl()
    {
        return 8ULL == (detail::ArmMotorsInt64_Reply_offset_of<ArmMotorsInt64_Reply, detail::ArmMotorsInt64_Reply_f>() + sizeof(int64_t));

    }};

#endif // _FAST_DDS_GENERATED_ARMMOTORSINT64_PUBSUBTYPES_H_

