// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ArmMotors.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ArmMotors.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define ArmMotors_Request_max_cdr_typesize 1ULL;
#define ArmMotors_Reply_max_cdr_typesize 1ULL;
#define ArmMotors_Request_max_key_cdr_typesize 0ULL;
#define ArmMotors_Reply_max_key_cdr_typesize 0ULL;

ArmMotors_Request::ArmMotors_Request()
{
    // boolean m_arm
    m_arm = false;

}

ArmMotors_Request::~ArmMotors_Request()
{
}

ArmMotors_Request::ArmMotors_Request(
        const ArmMotors_Request& x)
{
    m_arm = x.m_arm;
}

ArmMotors_Request::ArmMotors_Request(
        ArmMotors_Request&& x) noexcept 
{
    m_arm = x.m_arm;
}

ArmMotors_Request& ArmMotors_Request::operator =(
        const ArmMotors_Request& x)
{

    m_arm = x.m_arm;

    return *this;
}

ArmMotors_Request& ArmMotors_Request::operator =(
        ArmMotors_Request&& x) noexcept
{

    m_arm = x.m_arm;

    return *this;
}

bool ArmMotors_Request::operator ==(
        const ArmMotors_Request& x) const
{

    return (m_arm == x.m_arm);
}

bool ArmMotors_Request::operator !=(
        const ArmMotors_Request& x) const
{
    return !(*this == x);
}

size_t ArmMotors_Request::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ArmMotors_Request_max_cdr_typesize;
}

size_t ArmMotors_Request::getCdrSerializedSize(
        const ArmMotors_Request& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void ArmMotors_Request::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_arm;

}

void ArmMotors_Request::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_arm;
}

/*!
 * @brief This function sets a value in member arm
 * @param _arm New value for member arm
 */
void ArmMotors_Request::arm(
        bool _arm)
{
    m_arm = _arm;
}

/*!
 * @brief This function returns the value of member arm
 * @return Value of member arm
 */
bool ArmMotors_Request::arm() const
{
    return m_arm;
}

/*!
 * @brief This function returns a reference to member arm
 * @return Reference to member arm
 */
bool& ArmMotors_Request::arm()
{
    return m_arm;
}



size_t ArmMotors_Request::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ArmMotors_Request_max_key_cdr_typesize;
}

bool ArmMotors_Request::isKeyDefined()
{
    return false;
}

void ArmMotors_Request::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}


ArmMotors_Reply::ArmMotors_Reply()
{
    // boolean m_result
    m_result = false;

}

ArmMotors_Reply::~ArmMotors_Reply()
{
}

ArmMotors_Reply::ArmMotors_Reply(
        const ArmMotors_Reply& x)
{
    m_result = x.m_result;
}

ArmMotors_Reply::ArmMotors_Reply(
        ArmMotors_Reply&& x) noexcept 
{
    m_result = x.m_result;
}

ArmMotors_Reply& ArmMotors_Reply::operator =(
        const ArmMotors_Reply& x)
{

    m_result = x.m_result;

    return *this;
}

ArmMotors_Reply& ArmMotors_Reply::operator =(
        ArmMotors_Reply&& x) noexcept
{

    m_result = x.m_result;

    return *this;
}

bool ArmMotors_Reply::operator ==(
        const ArmMotors_Reply& x) const
{

    return (m_result == x.m_result);
}

bool ArmMotors_Reply::operator !=(
        const ArmMotors_Reply& x) const
{
    return !(*this == x);
}

size_t ArmMotors_Reply::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ArmMotors_Reply_max_cdr_typesize;
}

size_t ArmMotors_Reply::getCdrSerializedSize(
        const ArmMotors_Reply& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void ArmMotors_Reply::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_result;

}

void ArmMotors_Reply::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_result;
}

/*!
 * @brief This function sets a value in member result
 * @param _result New value for member result
 */
void ArmMotors_Reply::result(
        bool _result)
{
    m_result = _result;
}

/*!
 * @brief This function returns the value of member result
 * @return Value of member result
 */
bool ArmMotors_Reply::result() const
{
    return m_result;
}

/*!
 * @brief This function returns a reference to member result
 * @return Reference to member result
 */
bool& ArmMotors_Reply::result()
{
    return m_result;
}



size_t ArmMotors_Reply::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ArmMotors_Reply_max_key_cdr_typesize;
}

bool ArmMotors_Reply::isKeyDefined()
{
    return false;
}

void ArmMotors_Reply::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

